# Ansible Inventory - mounik-homelab
# Adapter les IPs et chemins SSH selon ton environnement

all:
  children:
    proxmox:
      hosts:
        pve01:
          ansible_host: 192.168.1.20
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
          pve_role: infrastructure
          pve_ip_suffix: "20"
        pve02:
          ansible_host: 192.168.1.21
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
          pve_role: personal-cloud
          pve_ip_suffix: "21"
        pve03:
          ansible_host: 192.168.1.22
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
          pve_role: ai-devops
          pve_ip_suffix: "22"

  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
